In [34]:
import numpy as np
import math

#make array
arr_test = np.random.randint(500, size = 5000)

# INSERTION SORT
## Pseudo Code (Ascent)
>for j = 2 to A.length<br>
>>    key = A[j]<br>
>>    //Insert A[j] in to the sorted sequence A[1 . . j-1]<br>
>>    i = j - 1<br>
>>    while i > 0 and A[i] > key:<br>
>>>        A[i+1] = A[i]<br>
>>>        i = i-1<br>
>>    A[i+1] = key <br>

For Insertion Sort I use the pseudo code directly.

In [40]:
A = np.array(tuple(arr_test))
for j in range(len(A))[1:]:
    k = A[j]
    i = j - 1
    while i >= 0 and A[i] > k:
        A[i + 1] = A[i]
        i = i-1
    A[i + 1] = k

#print the original array compare when use insertion sort.
print("ORIGINAL ORDER")
print(arr_test)
print("INSERTION SORT (Ascent)")
print(A)
#Make the array to check if my merge sort is correctly working or not
Test_i_as = np.array(tuple(A))

ORIGINAL ORDER
[387 273  88 ... 169  76 351]
INSERTION SORT (Ascent)
[  0   0   0 ... 499 499 499]


## Pseudo Code (descent)
>for j = 2 to A.length<br>
>>    key = A[j]<br>
>>    //Insert A[j] in to the sorted sequence A[1 . . j-1]<br>
>>    i = j - 1<br>
>>    while i > 0 and A[i] < key:<br>
>>>        A[i+1] = A[i]<br>
>>>        i = i-1<br>
>>    A[i+1] = key <br>

In [41]:
A = np.array(tuple(arr_test))
for j in range(len(A))[1:]:
    k = A[j]
    i = j - 1
    while i >= 0 and A[i] < k:
        A[i + 1] = A[i]
        i = i-1
    A[i + 1] = k

#print the original array compare when use insertion sort.
print("ORIGINAL ORDER")
print(arr_test)
print("INSERTION SORT (Descent)")
print(A)
#Make the array to check if my merge sort is correctly working or not
Test_i_des = np.array(tuple(A))

ORIGINAL ORDER
[387 273  88 ... 169  76 351]
INSERTION SORT (Descent)
[499 499 499 ...   0   0   0]


# MERGE SORT
## Pseudo Code (Ascent)

>n1 = q - p + 1<br>
>n2 = r - q<br>
>let L[1..n1 + 1] and R[1..n2 + 1] be new arrays<br>
>for i = 1 to n1<br>
>>    L[i] = A[p + i - 1]<br>
>for j = 1 to n2<br>
>>    R[j] = A[q + j]<br>
>L[n1 + 1] = inf<br>
>R[n2 + 1] = inf<br>
>i = 1<br>
>j = 1<br>
>for k = p to r<br>
>>    if L[i] <= R[j]<br>
>>>        A[k] = L[i]<br>
>>>        i = i + 1<br>
>>    else A[k] = R[j]<br>
>>>        j=j+1<br>


This is my test code adapt from the pseudo code, the first cell is messed one but working, the second is after I tidy it a bit.
Please read the comment in second one for explanation of code.

In [9]:
A = np.array(tuple(arr_test))
last = np.ones(1)
remain_sort = np.ones(1)

for x in range(1, int(math.log2(len(A)) // 1) + 1):
    for y in range(len(A))[::2 ** x]:

        #Sorting as normal
        if len(A[y:(y + (2 ** x))]) == 2 ** x:
            pseudo_A = A[y:(y + (2 ** x))]
            print(f"round{x}:{pseudo_A}")
            p = 0
            q = len(pseudo_A) // 2
            r = len(pseudo_A) 
            n1 = q - p
            n2 = r - q
            L = np.arange(n1 + 1)
            R = np.arange(n2 + 1)
            for i in range(n1):
                L[i] = pseudo_A[p + i]
            for j in range(n2):
                R[j] = pseudo_A[q + j]
            L[n1] = 9999
            R[n2] = 9999
            print(L,R)
            i = 0
            j = 0
            for k in range(r):
                if L[i] <= R[j]:
                    pseudo_A[k] = L[i]
                    i = i + 1
                elif R[j] < L[i]:
                    pseudo_A[k] = R[j]
                    j = j + 1
            print(f"result: {pseudo_A}")
            A[y:(y + (2 ** x))] = pseudo_A

        #sorting normal set before remain number with remain number
        if len(A[y:(y + (2 ** x))]) != 2 ** x and y == (len(A) // (2 ** x)) * (2**x):
            print("remain num: ")
            remain_A = A[-int(len(A) % (2 ** x)) - len(pseudo_A):]
            p = 0
            q = len(pseudo_A)
            r = len(remain_A)
            n1 = q - p
            n2 = r - q
            L = np.append(remain_A[p:q], 9999)
            R = np.append(remain_A[q:], 9999)
            print(L,R)
            i = 0
            j = 0
            for k in range(r):
                if L[i] <= R[j]:
                    remain_A[k] = L[i]
                    i = i + 1
                elif R[j] < L[i]:
                    remain_A[k] = R[j]
                    j = j + 1
            A[-int(len(A) % (2 ** x)) - len(pseudo_A):] = remain_A 
            print("Result Remain:", remain_A)
        
        #last merge
        if x == int(math.log2(len(A)) // 1) and y == 0:
            last = pseudo_A
            p = 0
            q = len(pseudo_A)
            r = len(A)
            print("Last")
            n1 = q - p
            n2 = r
            L = np.append(A[:q], 9999)
            R = np.append(A[q:], 9999)
            print(L,R)
            i = 0
            j = 0
            for k in range(r):
                if L[i] <= R[j]:
                    A[k] = L[i]
                    i = i + 1
                elif R[j] < L[i]:
                    A[k] = R[j]
                    j = j + 1
            break   

print("Merge Sort")
print(arr_test)
Test_m_as = np.array(tuple(A))
print(A)
print(all(Test_i_as[:] == Test_m_as[:]))

round1:[19 17]
[  19 9999] [  17 9999]
result: [17 19]
round1:[11  5]
[  11 9999] [   5 9999]
result: [ 5 11]
round1:[ 0 19]
[   0 9999] [  19 9999]
result: [ 0 19]
round1:[ 0 15]
[   0 9999] [  15 9999]
result: [ 0 15]
round1:[12  2]
[  12 9999] [   2 9999]
result: [ 2 12]
round2:[17 19  5 11]
[  17   19 9999] [   5   11 9999]
result: [ 5 11 17 19]
round2:[ 0 19  0 15]
[   0   19 9999] [   0   15 9999]
result: [ 0  0 15 19]
remain num: 
[   0    0   15   19 9999] [   2   12 9999]
Result Remain: [ 0  0  2 12 15 19]
round3:[ 5 11 17 19  0  0  2 12]
[   5   11   17   19 9999] [   0    0    2   12 9999]
result: [ 0  0  2  5 11 12 17 19]
Last
[   0    0    2    5   11   12   17   19 9999] [  15   19 9999]
Merge Sort
[19 17 11  5  0 19  0 15 12  2]
[ 0  0  2  5 11 12 15 17 19 19]
True


Here is the second edition of my merge sort code.

In [23]:
# I created three more array: 
# pseudo_A (in stead of A but not A to prevent my confusion), 
# remain_A (not sorted order array which is on the tail), 
# and last (for array I use in last merging process)
A = np.array(tuple(arr_test))
pseudo_A = np.ones(1)
last = np.ones(1)

# Make the function for merging process (moving the pointer and add it into array), 
# which is the most duplicate process without any different process in my code.
def merge_sort(Arr, L, R):
    i = 0
    j = 0
    for k in range(r):
        if L[i] <= R[j]:
            Arr[k] = L[i]
            i = i + 1
        elif R[j] < L[i]:
            Arr[k] = R[j]
            j = j + 1
    return Arr

# I have found that the index of y is increased by function 2^x when x equal to 1; increased by 1 
# until it reach the log2 of size of array, we want to sort it, bus as an only integer (not include decimals digit). 

for x in range(1, int(math.log2(len(A)) // 1) + 1):
    for y in range(len(A))[::2 ** x]:

        # Sorting as normal. It is developed from the pseudo code.
        if len(A[y:(y + (2 ** x))]) == 2 ** x:
            pseudo_A = A[y:(y + (2 ** x))]
            p = 0
            q = len(pseudo_A) // 2
            r = len(pseudo_A) 
            n1 = q - p
            n2 = r - q
            L = np.arange(n1 + 1)
            R = np.arange(n2 + 1)
            for i in range(n1):
                L[i] = pseudo_A[p + i]
            for j in range(n2):
                R[j] = pseudo_A[q + j]
            L[n1] = 9999
            R[n2] = 9999
            A[y:(y + (2 ** x))] = merge_sort(pseudo_A, L, R)
            print(f"Merging Array:\n{L} and {R}")
            print(f"Result is:\n{pseudo_A}")

        # Sorting normal set before remain number with remain number 
        # (to prevent 'the left tail of array not sorting' problem which make trouble when we merge for the last time)
        if len(A[y:(y + (2 ** x))]) != 2 ** x and y == (len(A) // (2 ** x)) * (2**x):
            remain_A = A[-int(len(A) % (2 ** x)) - len(pseudo_A):]
            p = 0
            q = len(pseudo_A)
            r = len(remain_A)
            n1 = q - p
            n2 = r - q
            L = np.append(remain_A[p:q], 9999)
            R = np.append(remain_A[q:], 9999)
            print(L,R)
            A[-int(len(A) % (2 ** x)) - len(pseudo_A):] = merge_sort(remain_A, L, R) 
            print(f"Merging Array:\n{L} and {R}")
            print(f"Result is:\n{remain_A}")
        
        # Last merging (to prevent the remain of product from dividing and it skip sorting process)
        if x == int(math.log2(len(A)) // 1) and y == 0:
            last = pseudo_A
            p = 0
            q = len(pseudo_A)
            r = len(A)
            n1 = q - p
            n2 = r
            L = np.append(A[:q], 9999)
            R = np.append(A[q:], 9999)
            A = merge_sort(A, L, R)
            print(f"Merging Array:\n{L} and {R}")
            print(f"Result is:\n{A}")
            break   

# Print the original order and new order using merge sort
print("ORIGINAL ORDER")
print(arr_test)
print("MERGE SORT (Ascent)")
print(A)

# Compare to insertion sort if there are any error or not (in case if we sort many many items).
Test_m_as = np.array(tuple(A))
print(all(Test_i_as[:] == Test_m_as[:]))

Merging Array:
[   7 9999] and [   9 9999]
Result is:
[7 9]
Merging Array:
[  12 9999] and [   9 9999]
Result is:
[ 9 12]
Merging Array:
[  14 9999] and [  18 9999]
Result is:
[14 18]
Merging Array:
[  16 9999] and [  15 9999]
Result is:
[15 16]
Merging Array:
[   7 9999] and [   5 9999]
Result is:
[5 7]
Merging Array:
[  14 9999] and [  10 9999]
Result is:
[10 14]
Merging Array:
[  12 9999] and [  14 9999]
Result is:
[12 14]
Merging Array:
[  13 9999] and [  15 9999]
Result is:
[13 15]
Merging Array:
[  19 9999] and [  17 9999]
Result is:
[17 19]
Merging Array:
[  14 9999] and [  10 9999]
Result is:
[10 14]
Merging Array:
[   0 9999] and [  16 9999]
Result is:
[ 0 16]
Merging Array:
[   7 9999] and [  10 9999]
Result is:
[ 7 10]
Merging Array:
[  16 9999] and [   7 9999]
Result is:
[ 7 16]
Merging Array:
[  15 9999] and [  18 9999]
Result is:
[15 18]
Merging Array:
[  16 9999] and [   6 9999]
Result is:
[ 6 16]
Merging Array:
[  18 9999] and [   5 9999]
Result is:
[ 5 18]
Merging Arra

## Pseudo Code (Descent)

>n1 = q - p + 1<br>
>n2 = r - q<br>
>let L[1..n1 + 1] and R[1..n2 + 1] be new arrays<br>
>for i = 1 to n1<br>
>>    L[i] = A[p + i - 1]<br>
>for j = 1 to n2<br>
>>    R[j] = A[q + j]<br>
>L[n1 + 1] = -inf<br>
>R[n2 + 1] = -inf<br>
>i = 1<br>
>j = 1<br>
>for k = p to r<br>
>>    if L[i] >= R[j]<br>
>>>        A[k] = L[i]<br>
>>>        i = i + 1<br>
>>    else A[k] = R[j]<br>
>>>        j=j+1<br>

In [42]:
# I created three more array: 
# pseudo_A (in stead of A but not A to prevent my confusion), 
# remain_A (not sorted order array which is on the tail), 
# and last (for array I use in last merging process)
A = np.array(tuple(arr_test))
pseudo_A = np.ones(1)
last = np.ones(1)

# Make the function for merging process (moving the pointer and add it into array), 
# which is the most duplicate process without any different process in my code.
def merge_sort(Arr, L, R):
    i = 0
    j = 0
    for k in range(r):
        if L[i] <= R[j]:
            Arr[k] = R[j]
            j = j + 1
        elif R[j] < L[i]:
            Arr[k] = L[i]
            i = i + 1
    return Arr

# I have found that the index of y is increased by function 2^x when x equal to 1; increased by 1 
# until it reach the log2 of size of array, we want to sort it, bus as an only integer (not include decimals digit). 

for x in range(1, int(math.log2(len(A)) // 1) + 1):
    for y in range(len(A))[::2 ** x]:

        # Sorting as normal. It is developed from the pseudo code.
        if len(A[y:(y + (2 ** x))]) == 2 ** x:
            pseudo_A = A[y:(y + (2 ** x))]
            p = 0
            q = len(pseudo_A) // 2
            r = len(pseudo_A) 
            n1 = q - p
            n2 = r - q
            L = np.arange(n1 + 1)
            R = np.arange(n2 + 1)
            for i in range(n1):
                L[i] = pseudo_A[p + i]
            for j in range(n2):
                R[j] = pseudo_A[q + j]
            L[n1] = -9999
            R[n2] = -9999
            A[y:(y + (2 ** x))] = merge_sort(pseudo_A, L, R)
            print(f"Merging Array:\n{L} and {R}")
            print(f"Result is:\n{pseudo_A}")

        # Sorting normal set before remain number with remain number 
        # (to prevent 'the left tail of array not sorting' problem which make trouble when we merge for the last time)
        if len(A[y:(y + (2 ** x))]) != 2 ** x and y == (len(A) // (2 ** x)) * (2 ** x):
            remain_A = A[-int(len(A) % (2 ** x)) - len(pseudo_A):]
            p = 0
            q = len(pseudo_A)
            r = len(remain_A)
            n1 = q - p
            n2 = r - q
            L = np.append(remain_A[p:q], -9999)
            R = np.append(remain_A[q:], -9999)
            print(L,R)
            A[-int(len(A) % (2 ** x)) - len(pseudo_A):] = merge_sort(remain_A, L, R) 
            print(f"Merging Array:\n{L} and {R}")
            print(f"Result is:\n{remain_A}")
        
        # Last merging (to prevent the remain of product from dividing and it skip sorting process)
        if x == int(math.log2(len(A)) // 1) and y == 0:
            last = pseudo_A
            p = 0
            q = len(pseudo_A)
            r = len(A)
            n1 = q - p
            n2 = r
            L = np.append(A[:q], -9999)
            R = np.append(A[q:], -9999)
            A = merge_sort(A, L, R)
            print(f"Merging Array:\n{L} and {R}")
            print(f"Result is:\n{A}")
            break   

# Print the original order and new order using merge sort
print("ORIGINAL ORDER")
print(arr_test)
print("MERGE SORT (Descent)")
print(A)

# Compare to insertion sort if there are any error or not (in case if we sort many many items).
Test_m_des = np.array(tuple(A))
print(all(Test_i_des[:] == Test_m_des[:]))

Merging Array:
[  387 -9999] and [  273 -9999]
Result is:
[387 273]
Merging Array:
[   88 -9999] and [  219 -9999]
Result is:
[219  88]
Merging Array:
[  148 -9999] and [  285 -9999]
Result is:
[285 148]
Merging Array:
[  231 -9999] and [  231 -9999]
Result is:
[231 231]
Merging Array:
[  447 -9999] and [  143 -9999]
Result is:
[447 143]
Merging Array:
[  408 -9999] and [  376 -9999]
Result is:
[408 376]
Merging Array:
[  327 -9999] and [  192 -9999]
Result is:
[327 192]
Merging Array:
[  318 -9999] and [   80 -9999]
Result is:
[318  80]
Merging Array:
[    6 -9999] and [  427 -9999]
Result is:
[427   6]
Merging Array:
[  497 -9999] and [  394 -9999]
Result is:
[497 394]
Merging Array:
[  181 -9999] and [   35 -9999]
Result is:
[181  35]
Merging Array:
[  254 -9999] and [  396 -9999]
Result is:
[396 254]
Merging Array:
[  397 -9999] and [  385 -9999]
Result is:
[397 385]
Merging Array:
[  386 -9999] and [  209 -9999]
Result is:
[386 209]
Merging Array:
[  376 -9999] and [  195 -9999]
R